[project]
name = "lumeh-org"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "libsass>=0.23.0",
    "mistletoe>=1.4.0",
    "python-slugify>=8.0.4",
    "pyyaml>=6.0.2",
]
