[[language]]
name = "python"
language-servers = ["ruff", "ty"]
auto-format = true

[language-server.ruff]
command = "uv"
args = ["run", "ruff", "server"]

[language-server.ty]
command = "uv"
args = ["run", "ty", "server"]
